stages:
  train:
    cmd: PYTHONPATH="." python lib/train.py
    params:
      - train
    deps:
      - lib/train.py
    outs:
      - data/train

  eval:
    cmd: PYTHONPATH="." python lib/eval.py
    params:
      - eval
    deps:
      - lib/eval.py
      - data/train
    outs:
      - data/eval
    metrics:
      - data/metrics.json
