train:
  test_size: 0.2
  features:
  - sepal length (cm)
  - sepal width (cm)
  - petal length (cm)
  - petal width (cm)
  model:
    model_class: sklearn.tree.DecisionTreeClassifier
    params: {min_samples_split: 2}

eval:

metrics:
- sklearn.metrics.precision_score:
    average: macro
- sklearn.metrics.recall_score:
    average: macro
- sklearn.metrics.accuracy_score
